import Mathlib

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace GSTCanonicalTailStateIso

/-- Ternary digit at vertical position `p`. -/
def digit3 (N p : Nat) : Nat := (N / 3^p) % 3

/-- Exact x4 carry generated by the lower ternary prefix below `p`. -/
def carry4 (N p : Nat) : Nat := (4 * (N % 3^p)) / 3^p

/-- The physical Graph-V2 Happy gate: digit two with carry zero or three. -/
def HappyCell (C d : Nat) : Prop := d = 2 ∧ (C = 0 ∨ C = 3)

/-- Existence of a physical Happy gate. -/
def Navigation (N : Nat) : Prop :=
  ∃ p : Nat, HappyCell (carry4 N p) (digit3 N p)

/-- Exact quotient projection through a low prefix. -/
theorem prefix_slice_quotient_exact
    (b P tail q : Nat)
    (hP : P < 3^b) :
    (P + 3^b * tail) / 3^(b+q) = tail / 3^q := by
  have hp : 0 < 3^b := Nat.pow_pos (by decide)
  rw [pow_add, ← Nat.div_div_eq_div_mul]
  rw [Nat.add_mul_div_left _ _ hp, Nat.div_eq_of_lt hP, Nat.zero_add]

/-- Exact ternary digit projection through a low prefix. -/
theorem prefix_slice_digit_exact
    (b P tail q : Nat)
    (hP : P < 3^b) :
    digit3 (P + 3^b * tail) (b+q) = digit3 tail q := by
  unfold digit3
  rw [prefix_slice_quotient_exact b P tail q hP]

private theorem prefix_mod_exact
    (b P tail : Nat)
    (hP : P < 3^b) :
    (P + 3^b * tail) % 3^b = P := by
  simpa [Nat.add_mod, Nat.mul_mod, Nat.mod_eq_of_lt hP]

private theorem prefix_deep_mod_exact
    (b P tail q : Nat)
    (hP : P < 3^b) :
    (P + 3^b * tail) % (3^b * 3^q) =
      P + 3^b * (tail % 3^q) := by
  rw [Nat.mod_mul]
  rw [prefix_mod_exact b P tail hP]
  have hp : 0 < 3^b := Nat.pow_pos (by decide)
  have hdiv : (P + 3^b * tail) / 3^b = tail := by
    rw [Nat.add_mul_div_left _ _ hp, Nat.div_eq_of_lt hP, Nat.zero_add]
  rw [hdiv]

/-- Exact carry projection.  If the fourfold low prefix remains below the cut,
its carry seed is zero and the tail carry is exposed literally. -/
theorem prefix_slice_carry_seed_zero
    (b P tail q : Nat)
    (hP : P < 3^b)
    (hseed : 4 * P < 3^b) :
    carry4 (P + 3^b * tail) (b+q) = carry4 tail q := by
  unfold carry4
  rw [pow_add]
  rw [prefix_deep_mod_exact b P tail q hP]
  rw [← Nat.div_div_eq_div_mul]
  have hp : 0 < 3^b := Nat.pow_pos (by decide)
  have hshape :
      4 * (P + 3^b * (tail % 3^q)) =
        4 * P + 3^b * (4 * (tail % 3^q)) := by ring
  rw [hshape, Nat.add_mul_div_left _ _ hp]
  rw [Nat.div_eq_of_lt hseed, Nat.zero_add]

/-- Exact physical state isomorphism after any seed-zero prefix cut. -/
theorem prefix_slice_happy_iff
    (b P tail q : Nat)
    (hP : P < 3^b)
    (hseed : 4 * P < 3^b) :
    HappyCell
        (carry4 (P + 3^b * tail) (b+q))
        (digit3 (P + 3^b * tail) (b+q)) ↔
      HappyCell (carry4 tail q) (digit3 tail q) := by
  unfold HappyCell
  rw [prefix_slice_digit_exact b P tail q hP]
  rw [prefix_slice_carry_seed_zero b P tail q hP hseed]

/-- A canonical prefix `1` is seed-zero at every cut of width at least two. -/
theorem one_prefix_bounds
    (b : Nat) (hb : 2 ≤ b) :
    1 < 3^b ∧ 4 < 3^b := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le hb
  have hk : 0 < 3^k := Nat.pow_pos (by decide)
  constructor <;> rw [pow_add] <;> norm_num <;> omega

/-- Canonical Tail Isomorphism: for `R = 1 + 3^b Q`, every physical Graph-V2
state at `b+j` is exactly the state of `Q` at `j`. -/
theorem canonical_tail_state_isomorphism
    (b Q j : Nat) (hb : 2 ≤ b) :
    digit3 (1 + 3^b * Q) (b+j) = digit3 Q j ∧
    carry4 (1 + 3^b * Q) (b+j) = carry4 Q j := by
  have hbounds := one_prefix_bounds b hb
  exact ⟨
    prefix_slice_digit_exact b 1 Q j hbounds.1,
    prefix_slice_carry_seed_zero b 1 Q j hbounds.1 (by simpa using hbounds.2)⟩

/-- Physical Happy-gate equivalence induced by the canonical tail cut. -/
theorem canonical_tail_happy_iff
    (b Q j : Nat) (hb : 2 ≤ b) :
    HappyCell
        (carry4 (1 + 3^b * Q) (b+j))
        (digit3 (1 + 3^b * Q) (b+j)) ↔
      HappyCell (carry4 Q j) (digit3 Q j) := by
  have hbounds := one_prefix_bounds b hb
  exact prefix_slice_happy_iff b 1 Q j hbounds.1 (by simpa using hbounds.2)

end GSTCanonicalTailStateIso
