import GSTPrefixOneLegacyCorollaries

#print axioms GSTCanonicalTailStateIso.canonical_tail_happy_iff
#print axioms GSTPerfectPowerTailNavigation.canonical_tail_projection
#print axioms GSTFourPowerOntologicalAdapter.creation_certificate_to_navigation
#print axioms GSTFourPowerOntologicalAdapter.gst_four_power_ontological_navigation_of_master
#print axioms GSTPrefixOneOntologicalEscape.gst_prefix_one_ontological_escape_of_master
#print axioms GSTSeedOneShift.navigation_prefixed_one_iff_seed_one
#print axioms GSTPrefixOneSeedCore.canonical_prefix_recurrence
#print axioms GSTPrefixOneSeedCore.gst_prefix_one_seed_one_parent_of_master
#print axioms GSTPrefixOneLegacyCorollaries.gst_prefix_one_navigation_lift_of_master
#print axioms GSTPrefixOneLegacyCorollaries.gst_prefix_one_atomic_collision_of_master
#print axioms GSTPrefixOneLegacyCorollaries.gst_prefix_one_information_bad_descends_of_master
