import GSTPrefixOneLegacyCorollaries

#print axioms GSTPerfectPowerTailNavigation.canonical_tail_projection
#print axioms GSTFourPowerOntologicalAdapter.gst_four_power_ontological_navigation_master
#print axioms GSTPrefixOneOntologicalEscape.gst_prefix_one_ontological_escape
#print axioms GSTSeedOneShift.navigation_prefixed_one_iff_seed_one
#print axioms GSTPrefixOneSeedCore.gst_prefix_one_seed_one_parent_unconditional
#print axioms GSTPrefixOneLegacyCorollaries.gst_prefix_one_navigation_lift
#print axioms GSTPrefixOneLegacyCorollaries.gst_prefix_one_atomic_collision
#print axioms GSTPrefixOneLegacyCorollaries.gst_prefix_one_information_bad_descends
