import GSTGraphV2TransparentWidthThree

#check GSTGraphV2TransparentWidthThree.power_width_three_exact_conservation_at_cut
#check GSTGraphV2TransparentWidthThree.power_three_step_collision_at_cut
#check GSTGraphV2TransparentWidthThree.power_happy_add_three_mul_at_cut

#print axioms GSTGraphV2TransparentWidthThree.power_width_three_exact_conservation_at_cut
#print axioms GSTGraphV2TransparentWidthThree.power_three_step_collision_at_cut
#print axioms GSTGraphV2TransparentWidthThree.power_happy_add_three_mul_at_cut
