import GSTGraphV2InfiniteControl

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace GSTGraphV2SeededPrefix

open GSTU2DEventTransport

/-- The complete lower ternary prefix already consumed before reading `q`
more digits of `x`.  Unlike a local carry label, `D` is retained exactly. -/
def seededResidue (D k x q : Nat) : Nat :=
  D + 3^k * (x % 3^q)

/-- The physical x4 carry generated by the complete seeded residue. -/
def seededCarry (D k x q : Nat) : Nat :=
  (4 * seededResidue D k x q) / 3^(k+q)

/-- The next ternary information digit of the unconsumed tail. -/
def seededDigit (x q : Nat) : Nat :=
  (x / 3^q) % 3

/-- Happy in the lossless seeded-prefix coordinates. -/
def SeedHappy (D k x q : Nat) : Prop :=
  HappyCell (seededCarry D k x q) (seededDigit x q)

/-- Consuming one ternary digit moves it into the exact lower prefix. -/
theorem seededResidue_strip
    (D k x q : Nat) :
    seededResidue D k x (q+1) =
      seededResidue
        (D + 3^k * (x % 3))
        (k+1)
        (x / 3)
        q := by
  unfold seededResidue
  rw [show 3^(q+1) = 3 * 3^q by
    rw [Nat.pow_succ]
    ring]
  rw [Nat.mod_mul]
  rw [Nat.pow_succ]
  ring

/-- The lossless strip leaves the physical carry unchanged. -/
theorem seededCarry_strip
    (D k x q : Nat) :
    seededCarry D k x (q+1) =
      seededCarry
        (D + 3^k * (x % 3))
        (k+1)
        (x / 3)
        q := by
  unfold seededCarry
  rw [seededResidue_strip]
  congr 2
  omega

/-- The unconsumed digit stream shifts by one exact ternary division. -/
theorem seededDigit_strip
    (x q : Nat) :
    seededDigit x (q+1) =
      seededDigit (x / 3) q := by
  unfold seededDigit
  rw [show 3^(q+1) = 3 * 3^q by
    rw [Nat.pow_succ]
    ring]
  rw [← Nat.div_div_eq_div_mul]

/-- Happy is invariant under the exact lossless vertical strip. -/
theorem seedHappy_strip
    (D k x q : Nat) :
    SeedHappy D k x (q+1) ↔
      SeedHappy
        (D + 3^k * (x % 3))
        (k+1)
        (x / 3)
        q := by
  unfold SeedHappy
  rw [seededCarry_strip, seededDigit_strip]


/-- Seed-zero lossless coordinates are the ordinary tail cell. -/
theorem seedHappy_zero_iff
    (x q : Nat) :
    SeedHappy 0 0 x q ↔
      HappyCell
        (GSTCanonicalSevenAxisBridge.carry4 x q)
        (GSTCanonicalSevenAxisBridge.digit3 x q) := by
  simp [SeedHappy, seededCarry, seededResidue, seededDigit,
    GSTCanonicalSevenAxisBridge.carry4,
    GSTCanonicalSevenAxisBridge.digit3]

/-- The lossless prefix `(D,k)=(1,1)` is exactly the existing seed-one
controller carry. -/
theorem seededCarry_one_one
    (x q : Nat) :
    seededCarry 1 1 x q =
      GSTGraphV2InfiniteControl.seededCarry 1 x q := by
  unfold seededCarry seededResidue GSTGraphV2InfiniteControl.seededCarry
  simp only [Nat.pow_one]
  have hshape :
      4 * (1 + 3 * (x % 3^q)) =
        1 + 3 * (1 + 4 * (x % 3^q)) := by ring
  rw [hshape]
  rw [show 3^(1+q) = 3 * 3^q by
    rw [pow_add]
    norm_num]
  rw [← Nat.div_div_eq_div_mul]
  rw [Nat.add_mul_div_left _ _ (by decide : 0 < 3)]
  simp

/-- Seed-one lossless coordinates coincide with the existing all-depth
controller predicate. -/
theorem seedHappy_one_iff
    (x q : Nat) :
    SeedHappy 1 1 x q ↔
      HappyCell
        (GSTGraphV2InfiniteControl.seededCarry 1 x q)
        (GSTCanonicalSevenAxisBridge.digit3 x q) := by
  unfold SeedHappy seededDigit
  rw [seededCarry_one_one]
  rfl

#check seededResidue_strip
#check seededCarry_strip
#check seededDigit_strip
#check seedHappy_strip
#check seedHappy_zero_iff
#check seedHappy_one_iff
#print axioms seedHappy_strip

end GSTGraphV2SeededPrefix
