import GSTInfiniteFourPowerNavigation

#check GSTInfiniteFourPowerNavigation.power_width_three_exact_conservation
#check GSTInfiniteFourPowerNavigation.power_width_three_u_derivative_positive
#check GSTInfiniteFourPowerNavigation.power_three_step_collision
#check GSTInfiniteFourPowerNavigation.four_power_happy_ge_three
#check GSTInfiniteFourPowerNavigation.gst_four_power_navigation_universal

#print axioms GSTInfiniteFourPowerNavigation.power_width_three_exact_conservation
#print axioms GSTInfiniteFourPowerNavigation.power_width_three_u_derivative_positive
#print axioms GSTInfiniteFourPowerNavigation.power_three_step_collision
#print axioms GSTInfiniteFourPowerNavigation.four_power_happy_ge_three
#print axioms GSTInfiniteFourPowerNavigation.gst_four_power_navigation_universal
