import GSTU2DAtomicBridge
import GSTU2DExactCrossingCharge

#check GSTU2DAtomicBridge.gst_u_charge_as_carry_potential
#check GSTU2DAtomicBridge.gst_coupled_potential_as_mixed_boundary
#check GSTU2DAtomicBridge.weighted_mixed_rectangle_emergence
#check GSTU2DAtomicBridge.weighted_info_boundary_exact

-- RED test for the Aug-23 stronger finite block theorem.
#check GSTU2DExactCrossingCharge.reverseCrossCode_ge_sharp_of_leading_happy