import GSTGraphV2InfiniteControlScratch

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace GSTInfiniteV2

/-!
# Exact cardinal-world master equation

This is the integer-cleared form of the handwritten world projection

    4 D_R(3/K) - E_R(3/K) = (K-1) C_R(3/K).

Rather than use rational functions, we recursively clear the K-denominators.
The theorem is exact over Nat.  The coefficient K-1 therefore exists for every
world cardinality K simultaneously.
-/

/-- Physical output digit generated by one x4/base-3 GST cell. -/
def gstOutputDigitS (R p : Nat) : Nat :=
  (gstCarryS R p + 4 * gstDigitS R p) % 3

/-- Exact one-cell conservation. -/
theorem gst_cell_conservation_cardinalS (R p : Nat) :
    gstCarryS R p + 4 * gstDigitS R p =
      gstOutputDigitS R p + 3 * gstCarryS R (p+1) := by
  have hcarry := gstCarryS_forward_exact_all R p
  unfold gstOutputDigitS
  have h := Nat.mod_add_div
    (gstCarryS R p + 4 * gstDigitS R p) 3
  rw [hcarry]
  omega

/-- K-cleared input digit polynomial through depth L. -/
def gstCardinalInputEvalS (R K : Nat) : Nat → Nat
  | 0 => 0
  | L+1 =>
      K * gstCardinalInputEvalS R K L +
        K * 3^L * gstDigitS R L

/-- K-cleared output/event digit polynomial through depth L. -/
def gstCardinalOutputEvalS (R K : Nat) : Nat → Nat
  | 0 => 0
  | L+1 =>
      K * gstCardinalOutputEvalS R K L +
        K * 3^L * gstOutputDigitS R L

/-- K-cleared carry polynomial.  The coefficient at depth j is weighted by
3^j K^(L-j); this recursion is exactly that Horner evaluation. -/
def gstCardinalCarryEvalS (R K : Nat) : Nat → Nat
  | 0 => 0
  | L+1 =>
      K * gstCardinalCarryEvalS R K L +
        3^(L+1) * gstCarryS R (L+1)

/-- Finite cardinal-world identity with the exact terminal boundary carry
retained.  No assumption that the wave is terminal is made here. -/
theorem gst_cardinal_master_with_boundaryS
    (R K L : Nat) :
    4 * gstCardinalInputEvalS R K L +
        gstCardinalCarryEvalS R K L =
      gstCardinalOutputEvalS R K L +
        K * gstCardinalCarryEvalS R K L +
        3^L * gstCarryS R L := by
  induction L with
  | zero =>
      simp [gstCardinalInputEvalS, gstCardinalOutputEvalS,
        gstCardinalCarryEvalS, gstCarryS]
  | succ L ih =>
      have hlocal := gst_cell_conservation_cardinalS R L
      rw [gstCardinalInputEvalS, gstCardinalOutputEvalS,
        gstCardinalCarryEvalS]
      calc
        4 * (K * gstCardinalInputEvalS R K L +
              K * 3^L * gstDigitS R L) +
            (K * gstCardinalCarryEvalS R K L +
              3^(L+1) * gstCarryS R (L+1)) =
          K * (4 * gstCardinalInputEvalS R K L +
              gstCardinalCarryEvalS R K L) +
            K * 3^L * (4 * gstDigitS R L) +
            3^(L+1) * gstCarryS R (L+1) := by ring
        _ = K * (gstCardinalOutputEvalS R K L +
              K * gstCardinalCarryEvalS R K L +
              3^L * gstCarryS R L) +
            K * 3^L * (4 * gstDigitS R L) +
            3^(L+1) * gstCarryS R (L+1) := by rw [ih]
        _ = K * gstCardinalOutputEvalS R K L +
            K * K * gstCardinalCarryEvalS R K L +
            K * 3^L *
              (gstCarryS R L + 4 * gstDigitS R L) +
            3^(L+1) * gstCarryS R (L+1) := by ring
        _ = K * gstCardinalOutputEvalS R K L +
            K * K * gstCardinalCarryEvalS R K L +
            K * 3^L *
              (gstOutputDigitS R L + 3 * gstCarryS R (L+1)) +
            3^(L+1) * gstCarryS R (L+1) := by rw [hlocal]
        _ = (K * gstCardinalOutputEvalS R K L +
              K * 3^L * gstOutputDigitS R L) +
            K * (K * gstCardinalCarryEvalS R K L +
              3^(L+1) * gstCarryS R (L+1)) +
            3^(L+1) * gstCarryS R (L+1) := by
              rw [Nat.pow_succ]
              ring

/-- Four times any natural fits below its own next ternary support scale. -/
theorem gst_four_mul_self_lt_three_pow_succS :
    ∀ R : Nat, 4*R < 3^(R+1)
  | 0 => by decide
  | R+1 => by
      have ih : 4*R < 3^(R+1) :=
        gst_four_mul_self_lt_three_pow_succS R
      have hp : 2 ≤ 3^(R+1) := by
        have hpos : 0 < 3^R := Nat.pow_pos (by decide)
        rw [Nat.pow_succ]
        omega
      rw [show (R+1)+1 = (R+1)+1 by rfl, Nat.pow_succ]
      omega

/-- At the true natural support ceiling R+1 the GST carry is exactly zero. -/
theorem gst_carry_zero_at_natural_ceilingS (R : Nat) :
    gstCarryS R (R+1) = 0 := by
  unfold gstCarryS
  have hR : R < 3^(R+1) := gst_self_lt_three_pow_succS R
  rw [Nat.mod_eq_of_lt hR]
  exact Nat.div_eq_of_lt (gst_four_mul_self_lt_three_pow_succS R)

/-- Exact integer cardinal-world master equation. -/
theorem gst_cardinal_master_exactS
    (R K : Nat) (hK : 1 ≤ K) :
    4 * gstCardinalInputEvalS R K (R+1) =
      gstCardinalOutputEvalS R K (R+1) +
        (K-1) * gstCardinalCarryEvalS R K (R+1) := by
  have h := gst_cardinal_master_with_boundaryS R K (R+1)
  rw [gst_carry_zero_at_natural_ceilingS, Nat.mul_zero, Nat.add_zero] at h
  have hKshape : K = 1 + (K-1) := by omega
  rw [hKshape] at h
  have hmul :
      (1 + (K-1)) * gstCardinalCarryEvalS R K (R+1) =
        gstCardinalCarryEvalS R K (R+1) +
          (K-1) * gstCardinalCarryEvalS R K (R+1) := by ring
  rw [hmul] at h
  omega

/-- World K=6 exposes coefficient five exactly. -/
theorem gst_cardinal_master_sixS (R : Nat) :
    4 * gstCardinalInputEvalS R 6 (R+1) =
      gstCardinalOutputEvalS R 6 (R+1) +
        5 * gstCardinalCarryEvalS R 6 (R+1) := by
  simpa using gst_cardinal_master_exactS R 6 (by decide)

/-- World K=8 exposes the handwritten factor seven exactly. -/
theorem gst_cardinal_master_eight_factor_sevenS (R : Nat) :
    4 * gstCardinalInputEvalS R 8 (R+1) =
      gstCardinalOutputEvalS R 8 (R+1) +
        7 * gstCardinalCarryEvalS R 8 (R+1) := by
  simpa using gst_cardinal_master_exactS R 8 (by decide)

/-- World K=12 gives the mod-11 local V2 coefficient. -/
theorem gst_cardinal_master_twelve_factor_elevenS (R : Nat) :
    4 * gstCardinalInputEvalS R 12 (R+1) =
      gstCardinalOutputEvalS R 12 (R+1) +
        11 * gstCardinalCarryEvalS R 12 (R+1) := by
  simpa using gst_cardinal_master_exactS R 12 (by decide)

/-- The first equal-scale 36-state world has coefficient 35=6^2-1. -/
theorem gst_cardinal_master_thirtysix_factor_thirtyfiveS (R : Nat) :
    4 * gstCardinalInputEvalS R 36 (R+1) =
      gstCardinalOutputEvalS R 36 (R+1) +
        35 * gstCardinalCarryEvalS R 36 (R+1) := by
  simpa using gst_cardinal_master_exactS R 36 (by decide)

/-- Every equal-scale six-world cardinality carries coefficient 6^q-1. -/
theorem gst_cardinal_master_six_powS
    (R q : Nat) :
    4 * gstCardinalInputEvalS R (6^q) (R+1) =
      gstCardinalOutputEvalS R (6^q) (R+1) +
        (6^q-1) * gstCardinalCarryEvalS R (6^q) (R+1) := by
  have hK : 1 ≤ 6^q := by positivity
  exact gst_cardinal_master_exactS R (6^q) hK

/-- Infinite family packaging: every positive world cardinality is controlled
by the same exact equation, and the six-world subfamily is obtained simply by
choosing K=6^q. -/
def GSTInfiniteCardinalMasterS (R : Nat) : Prop :=
  ∀ K, 1 ≤ K →
    4 * gstCardinalInputEvalS R K (R+1) =
      gstCardinalOutputEvalS R K (R+1) +
        (K-1) * gstCardinalCarryEvalS R K (R+1)

theorem gst_infinite_cardinal_masterS
    (R : Nat) : GSTInfiniteCardinalMasterS R := by
  intro K hK
  exact gst_cardinal_master_exactS R K hK

end GSTInfiniteV2
