name: Lean Action CI
on:
  push:
    branches: ['**']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Test
        run: echo "hello"
